### PR TITLE
Added classes to parent element for styling purposes

### PR DESCRIPTION
**Pull request by jackmahoney**
Add class to parent of input element before wrapping with container classes to allow for easier styling.

### CODE REVIEW

**Comment by markushausammann** [comment]
Very good! It also helps a lot if you want to maintain graceful degradation. At the moment I have to do selects like this: 

```
.labelright + span.checkbox-label
```

To select only if prettyCheckable is used.

**Comment by arthurgouveia** [comment]
Hello, @jackmahoney.

Every input gets a wrapper class according to it's type: prettycheckbox or prettyradio.
Aside from that, if you indicate data-class="has-pretty-child" on the inputs you want the class added to, the plugin will take care of it.

Can you try that?

**Comment by arthurgouveia** [comment]
My bad: it's data-customClass

**Comment by jackmahoney** [comment]
Hi @arthurgouveia, thanks for you work on this plugin.

Good point, but this commit adds a class to the parent of the initial input[type=checkbox] not the wrappers that are created for the fake checkbox divs.

**Pull request closed without merging**
