### PR TITLE
Makes prettyCheckable gracefully degradable

### PR DESCRIPTION
**Pull request by markushausammann**
The below changes enables the user to write markup that degrades gracefully, if the prettCheckable js is switched off.

If markup is written like this (degradable):

```
<label class="checkbox" for="example">
    <input type="checkbox"
           name="example"
           id="example"
           value="1"
           class="pretty"
           /><span>Some label text</span>
</label>
```

PrettyCheckable will find 'Some label text', store it and then remove the span and use the label text.
In case prettyCheckable is not available, normal checkboxes will be rendered.

If the markup is written like this (non-degradable):

```
<input type="checkbox"
       name="example"
       id="example"
       value="1"
       class="pretty"
       data-label="Some label text"
       />
```

The text from the data attribute will be used as it was before.

The only **important implication for the documentation** is, that the label text needs to be wrapped in a span element!

### CODE REVIEW

**Comment by markushausammann** [comment]
I implemented the necessary code as method of the Plugin, if you find this stupid, please refactor or tell me how to.

**Comment by WilliamVercken** [comment]
I'd like to have your solution integrated too.
What's your opinion @arthurgouveia ? Is there a chance to see that coming ?

**Comment by markushausammann** [comment]
We are throwing prettyCheckable out, so I'm not interested in this anymore. The product doesn't develop fast enough to be used in production.

**Comment by WilliamVercken** [comment]
The problem is still here, why did you close this issue... ?

**Comment by arthurgouveia** [comment]
No reason to close it.

This has not being merged yet because I'm still trying to figure out a better way to have the label detection secure enough to make it automatic while still very much flexible.

The proposed solution requires specific DOM structure to work.

**Pull request closed without merging**
