### PR TITLE
Bootstrap CSS

### PR DESCRIPTION
**Pull request by fungio**
This CSS makes checkboxes & radios look like Bootstrap (http://twitter.github.com/bootstrap/)
The background-images are replaced by Font-Awesome icons
--> The Font-awesome CSS/font is required (http://fortawesome.github.com/Font-Awesome)

Demo: http://jsfiddle.net/fungio/8pYPA/

### CODE REVIEW

**Comment by arthurgouveia** [comment]
Holy shit. I loved this.

Next week I'll be checking with more details and merging the pull requests!

**Comment by fungio** [comment]
I'm glad you like it. This css makes it easy to change the checkbox/radio colors. http://jsfiddle.net/sqSuN/

**Comment by arthurgouveia** [comment]
@fungio, would you mind forking the gh-pages branch and providing documentation with examples?

**Comment by markushausammann** [comment]
sup?

**Comment by pepperstreet** [comment]
Exactly what I am looking for! Wanted something like "BootMetro" project does with "IcoMoon" font.
See under headline "Checkboxes and Radios":
http://aozora.github.io/bootmetro/docs/docs-css.html#forms

**Comment by pepperstreet** [comment]
@fungio 
I tried the jsfiddle demo, but I am not sure about customization. Also not sure about the result in my browser. It looks incomplete or wrong to me. Should it really display those squares/rectangles? Please, see screenshot:
prettycheckable_with_fontawesome_jsfiddle

I tried the latest FontAwesome from CDN... and there are some pretty simple icons like:

icon-circle f111
icon-sign-blank f0c8

1.) How to use them instead?
2.) There are also nice pre made icons for checkboxes, i.e. "icon-check" and "icon-check-empty". Is it possible to use those as well, and switch between them.

Thanks in advance.

**Pull request closed without merging**
