### PR TITLE
Updated PSD file including the disabled controls

### PR DESCRIPTION
**Pull request by markushausammann**
neutral monochrome version

### CODE REVIEW

**Comment by arthurgouveia** [comment]
Hello again, @markushausammann.

I'll be updating the PSD file with the disabled checkbox and radio at some point today, like I said moments ago. I do not think that having a separate file and therefore a separate request a good practice. This will cause a flicker effect.

The disabled versions will be on the same file(sprite) and the CSS is already prepared for that, having the correct background-position, instead of a different background-image.

Thanks.

**Comment by markushausammann** [comment]
I don't get you, the PSD I made is exactly 300x30 and results in exactly the PNG needed for the CSS.

**Comment by arthurgouveia** [comment]
You made a PSD, not a PNG. If you send me a PSD, I'll have to overwrite the one from the landing page. You would need to send me a PNG, named according to the other ones that already exist.

**Comment by markushausammann** [comment]
I was always talking about a PSD, there isn't any in the repo.

**Comment by arthurgouveia** [comment]
https://github.com/arthurgouveia/prettyCheckable/tree/gh-pages/goodies

**Comment by markushausammann** [comment]
Well, ok, it's up to you how you want to organized your software but I would find it much easier to deal with everything, if the content wasn't split up into different repositories. I'm not gonna clone the pages too.

**Comment by arthurgouveia** [comment]
Nobody ever clones gh-pages repos, unless they want to create or modify a page for the plugin as well.

I just don't want people downloading the plugin to use with the PSD inside of it if they don't need further customization. The plugin has the code ready for use on master repo and it's description and demo on the gh-pages repo, as a bunch of others do.

If you're going to modify this pull-request by removing your PSD and uploading a PNG with the new theme you're proposing, I'll be happy to merge it.

**Pull request closed without merging**
